/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author prestonaudu
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aplb = new javax.swing.JButton();
        AdminPageTabs = new javax.swing.JTabbedPane();
        appdt = new javax.swing.JPanel();
        apvpt = new javax.swing.JPanel();
        apvpl = new javax.swing.JLabel();
        appdlnf = new javax.swing.JTextField();
        appdnl = new javax.swing.JLabel();
        appdln = new javax.swing.JLabel();
        appdfnf = new javax.swing.JTextField();
        appddob = new javax.swing.JLabel();
        appdtpno = new javax.swing.JLabel();
        appdemad = new javax.swing.JLabel();
        appdtlpno = new javax.swing.JTextField();
        appdemadd = new javax.swing.JTextField();
        appddobs = new javax.swing.JTextField();
        appdlg = new javax.swing.JLabel();
        appdgcbm = new javax.swing.JCheckBox();
        appdgcbf = new javax.swing.JCheckBox();
        appdcb = new javax.swing.JButton();
        appdab = new javax.swing.JButton();
        apapt = new javax.swing.JPanel();
        apvplf = new javax.swing.JLabel();
        appdvpfl1 = new javax.swing.JLabel();
        appdvpfl2 = new javax.swing.JLabel();
        appdvpfl3 = new javax.swing.JLabel();
        apsptf = new javax.swing.JTextField();
        apsplntf = new javax.swing.JTextField();
        apsppid = new javax.swing.JTextField();
        apspsb = new javax.swing.JButton();
        apddt = new javax.swing.JPanel();
        apvpt1 = new javax.swing.JPanel();
        apvdl = new javax.swing.JLabel();
        appdlnf1 = new javax.swing.JTextField();
        apddnl = new javax.swing.JLabel();
        apddln = new javax.swing.JLabel();
        appdfnf1 = new javax.swing.JTextField();
        apdddob = new javax.swing.JLabel();
        apddtpno = new javax.swing.JLabel();
        apddemad = new javax.swing.JLabel();
        appdtlpno1 = new javax.swing.JTextField();
        appdemadd1 = new javax.swing.JTextField();
        appddobs1 = new javax.swing.JTextField();
        apddlg = new javax.swing.JLabel();
        apddgcbm = new javax.swing.JCheckBox();
        apddgcbf = new javax.swing.JCheckBox();
        apddcb = new javax.swing.JButton();
        apddab = new javax.swing.JButton();
        apddemad2 = new javax.swing.JLabel();
        appdemadd3 = new javax.swing.JTextField();
        apapt1 = new javax.swing.JPanel();
        apvplf1 = new javax.swing.JLabel();
        apsptf1 = new javax.swing.JTextField();
        apsplntf1 = new javax.swing.JTextField();
        appdvpfl4 = new javax.swing.JLabel();
        appdvpfl5 = new javax.swing.JLabel();
        appdvpfl6 = new javax.swing.JLabel();
        apsppid1 = new javax.swing.JTextField();
        apspsb1 = new javax.swing.JButton();
        aprdt = new javax.swing.JPanel();
        apvpt2 = new javax.swing.JPanel();
        apvdl1 = new javax.swing.JLabel();
        appdlnf2 = new javax.swing.JTextField();
        apddnl1 = new javax.swing.JLabel();
        apddln1 = new javax.swing.JLabel();
        appdfnf2 = new javax.swing.JTextField();
        apdddob1 = new javax.swing.JLabel();
        apddtpno1 = new javax.swing.JLabel();
        apddemad1 = new javax.swing.JLabel();
        appdtlpno2 = new javax.swing.JTextField();
        appdemadd2 = new javax.swing.JTextField();
        appddobs2 = new javax.swing.JTextField();
        apddlg1 = new javax.swing.JLabel();
        apddgcbm1 = new javax.swing.JCheckBox();
        apddgcbf1 = new javax.swing.JCheckBox();
        apddcb1 = new javax.swing.JButton();
        apddab1 = new javax.swing.JButton();
        apapt2 = new javax.swing.JPanel();
        apvplf2 = new javax.swing.JLabel();
        appdvpfl7 = new javax.swing.JLabel();
        appdvpfl8 = new javax.swing.JLabel();
        apsptf2 = new javax.swing.JTextField();
        apsplntf2 = new javax.swing.JTextField();
        apspsb2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adsridtf = new javax.swing.JTextField();
        apal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aplb.setText("LogOut");
        aplb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplbActionPerformed(evt);
            }
        });

        apvpt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        apvpl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        apvpl.setText("Add Patient");

        appdlnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdlnfActionPerformed(evt);
            }
        });

        appdnl.setText("First Name");

        appdln.setText("Last Name");

        appdfnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdfnfActionPerformed(evt);
            }
        });

        appddob.setText("Date of Birth");

        appdtpno.setText("Telephone No.");

        appdemad.setText("Email Address");

        appdlg.setText("Gender");

        appdgcbm.setText("Male");

        appdgcbf.setText("Female");
        appdgcbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdgcbfActionPerformed(evt);
            }
        });

        appdcb.setText("Clear");
        appdcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdcbActionPerformed(evt);
            }
        });

        appdab.setText("Add");

        javax.swing.GroupLayout apvptLayout = new javax.swing.GroupLayout(apvpt);
        apvpt.setLayout(apvptLayout);
        apvptLayout.setHorizontalGroup(
            apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apvptLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apvptLayout.createSequentialGroup()
                        .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appdnl)
                            .addComponent(appdln)
                            .addComponent(appddob, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appddobs, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(appdlnf)
                            .addComponent(appdfnf)))
                    .addGroup(apvptLayout.createSequentialGroup()
                        .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(appdemad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appdtpno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(appdlg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appdtlpno)
                            .addComponent(appdemadd, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addGroup(apvptLayout.createSequentialGroup()
                                .addComponent(appdgcbm)
                                .addGap(18, 18, 18)
                                .addComponent(appdgcbf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvptLayout.createSequentialGroup()
                        .addComponent(appdab)
                        .addGap(18, 18, 18)
                        .addComponent(appdcb)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvptLayout.createSequentialGroup()
                        .addComponent(apvpl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        apvptLayout.setVerticalGroup(
            apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apvptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvpl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdnl)
                    .addComponent(appdfnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdln)
                    .addComponent(appdlnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appddob)
                    .addComponent(appddobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdtpno)
                    .addComponent(appdtlpno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdemad)
                    .addComponent(appdemadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdlg)
                    .addComponent(appdgcbm)
                    .addComponent(appdgcbf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(apvptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdcb)
                    .addComponent(appdab))
                .addContainerGap())
        );

        apapt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        apvplf.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        apvplf.setText("Search Patient");

        appdvpfl1.setText("Last Name");

        appdvpfl2.setText("First Name");

        appdvpfl3.setText("Patient ID");

        apspsb.setText("Search");

        javax.swing.GroupLayout apaptLayout = new javax.swing.GroupLayout(apapt);
        apapt.setLayout(apaptLayout);
        apaptLayout.setHorizontalGroup(
            apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apaptLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(apvplf, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(apaptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apaptLayout.createSequentialGroup()
                        .addGroup(apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appdvpfl2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appdvpfl1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apsptf, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(apsplntf)))
                    .addGroup(apaptLayout.createSequentialGroup()
                        .addComponent(appdvpfl3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apsppid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apspsb)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        apaptLayout.setVerticalGroup(
            apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apaptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvplf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl2)
                    .addComponent(apsptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl1)
                    .addComponent(apsplntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(apaptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl3)
                    .addComponent(apsppid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apspsb))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout appdtLayout = new javax.swing.GroupLayout(appdt);
        appdt.setLayout(appdtLayout);
        appdtLayout.setHorizontalGroup(
            appdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appdtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apvpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apapt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        appdtLayout.setVerticalGroup(
            appdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appdtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apapt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        AdminPageTabs.addTab("Patent Details", appdt);

        apvpt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        apvdl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        apvdl.setText("Add Doctor");

        appdlnf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdlnf1ActionPerformed(evt);
            }
        });

        apddnl.setText("First Name");

        apddln.setText("Last Name");

        appdfnf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdfnf1ActionPerformed(evt);
            }
        });

        apdddob.setText("Date of Birth");

        apddtpno.setText("Telephone No.");

        apddemad.setText("Email Address");

        apddlg.setText("Gender");

        apddgcbm.setText("Male");
        apddgcbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apddgcbmActionPerformed(evt);
            }
        });

        apddgcbf.setText("Female");
        apddgcbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apddgcbfActionPerformed(evt);
            }
        });

        apddcb.setText("Clear");
        apddcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apddcbActionPerformed(evt);
            }
        });

        apddab.setText("Add");

        apddemad2.setText("Department");

        javax.swing.GroupLayout apvpt1Layout = new javax.swing.GroupLayout(apvpt1);
        apvpt1.setLayout(apvpt1Layout);
        apvpt1Layout.setHorizontalGroup(
            apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apvpt1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apvpt1Layout.createSequentialGroup()
                        .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apddnl)
                            .addComponent(apddln)
                            .addComponent(apdddob, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appddobs1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(appdlnf1)
                            .addComponent(appdfnf1)))
                    .addGroup(apvpt1Layout.createSequentialGroup()
                        .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(apddemad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apddtpno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(apddlg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apddemad2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appdtlpno1)
                            .addComponent(appdemadd1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(appdemadd3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addGroup(apvpt1Layout.createSequentialGroup()
                                .addComponent(apddgcbm)
                                .addGap(18, 18, 18)
                                .addComponent(apddgcbf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvpt1Layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvpt1Layout.createSequentialGroup()
                        .addComponent(apddab)
                        .addGap(18, 18, 18)
                        .addComponent(apddcb)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvpt1Layout.createSequentialGroup()
                        .addComponent(apvdl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        apvpt1Layout.setVerticalGroup(
            apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apvpt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvdl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddnl)
                    .addComponent(appdfnf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddln)
                    .addComponent(appdlnf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apdddob)
                    .addComponent(appddobs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddtpno)
                    .addComponent(appdtlpno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddemad)
                    .addComponent(appdemadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdemadd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apddemad2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddgcbm)
                    .addComponent(apddgcbf)
                    .addComponent(apddlg))
                .addGap(18, 18, 18)
                .addGroup(apvpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddab)
                    .addComponent(apddcb))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        apapt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        apvplf1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        apvplf1.setText("Search Doctor");

        appdvpfl4.setText("Last Name");

        appdvpfl5.setText("First Name");

        appdvpfl6.setText("Doctor ID");

        apspsb1.setText("Search");

        javax.swing.GroupLayout apapt1Layout = new javax.swing.GroupLayout(apapt1);
        apapt1.setLayout(apapt1Layout);
        apapt1Layout.setHorizontalGroup(
            apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apapt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apapt1Layout.createSequentialGroup()
                        .addGroup(apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appdvpfl5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appdvpfl4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apsptf1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(apsplntf1)))
                    .addGroup(apapt1Layout.createSequentialGroup()
                        .addComponent(appdvpfl6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apsppid1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apspsb1)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apapt1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apvplf1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        apapt1Layout.setVerticalGroup(
            apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apapt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvplf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl5)
                    .addComponent(apsptf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl4)
                    .addComponent(apsplntf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(apapt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl6)
                    .addComponent(apsppid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apspsb1))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout apddtLayout = new javax.swing.GroupLayout(apddt);
        apddt.setLayout(apddtLayout);
        apddtLayout.setHorizontalGroup(
            apddtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apddtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apddtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apvpt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apapt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        apddtLayout.setVerticalGroup(
            apddtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apddtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvpt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(apapt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AdminPageTabs.addTab("Doctor Details", apddt);

        apvpt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        apvdl1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        apvdl1.setText("Add Receptionist");

        appdlnf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdlnf2ActionPerformed(evt);
            }
        });

        apddnl1.setText("First Name");

        apddln1.setText("Last Name");

        appdfnf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdfnf2ActionPerformed(evt);
            }
        });

        apdddob1.setText("Date of Birth");

        apddtpno1.setText("Telephone No.");

        apddemad1.setText("Email Address");

        apddlg1.setText("Gender");

        apddgcbm1.setText("Male");

        apddgcbf1.setText("Female");
        apddgcbf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apddgcbf1ActionPerformed(evt);
            }
        });

        apddcb1.setText("Clear");
        apddcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apddcb1ActionPerformed(evt);
            }
        });

        apddab1.setText("Add");

        javax.swing.GroupLayout apvpt2Layout = new javax.swing.GroupLayout(apvpt2);
        apvpt2.setLayout(apvpt2Layout);
        apvpt2Layout.setHorizontalGroup(
            apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apvpt2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apvpt2Layout.createSequentialGroup()
                        .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apddnl1)
                            .addComponent(apddln1)
                            .addComponent(apdddob1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appddobs2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(appdlnf2)
                            .addComponent(appdfnf2)))
                    .addGroup(apvpt2Layout.createSequentialGroup()
                        .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(apddemad1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apddtpno1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(apddlg1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appdtlpno2)
                            .addComponent(appdemadd2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addGroup(apvpt2Layout.createSequentialGroup()
                                .addComponent(apddgcbm1)
                                .addGap(18, 18, 18)
                                .addComponent(apddgcbf1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvpt2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvpt2Layout.createSequentialGroup()
                        .addComponent(apddab1)
                        .addGap(41, 41, 41)
                        .addComponent(apddcb1)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apvpt2Layout.createSequentialGroup()
                        .addComponent(apvdl1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        apvpt2Layout.setVerticalGroup(
            apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apvpt2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvdl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddnl1)
                    .addComponent(appdfnf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddln1)
                    .addComponent(appdlnf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apdddob1)
                    .addComponent(appddobs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddtpno1)
                    .addComponent(appdtlpno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddemad1)
                    .addComponent(appdemadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddlg1)
                    .addComponent(apddgcbm1)
                    .addComponent(apddgcbf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(apvpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apddcb1)
                    .addComponent(apddab1))
                .addContainerGap())
        );

        apapt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        apvplf2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        apvplf2.setText("View Receptionist");

        appdvpfl7.setText("Last Name");

        appdvpfl8.setText("First Name");

        apspsb2.setText("Search");

        jLabel1.setText("Receptionist ID");

        adsridtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adsridtfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apapt2Layout = new javax.swing.GroupLayout(apapt2);
        apapt2.setLayout(apapt2Layout);
        apapt2Layout.setHorizontalGroup(
            apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apapt2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(apapt2Layout.createSequentialGroup()
                        .addGroup(apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appdvpfl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appdvpfl8, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apsplntf2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apsptf2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(apapt2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adsridtf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apspsb2)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apapt2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(apvplf2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        apapt2Layout.setVerticalGroup(
            apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apapt2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvplf2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl8)
                    .addComponent(apsptf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdvpfl7)
                    .addComponent(apsplntf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(apapt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apspsb2)
                    .addComponent(jLabel1)
                    .addComponent(adsridtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aprdtLayout = new javax.swing.GroupLayout(aprdt);
        aprdt.setLayout(aprdtLayout);
        aprdtLayout.setHorizontalGroup(
            aprdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aprdtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aprdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apvpt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apapt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        aprdtLayout.setVerticalGroup(
            aprdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aprdtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apvpt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apapt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AdminPageTabs.addTab("Receptionist Details", aprdt);

        apal.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        apal.setText("Admin Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aplb)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminPageTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(apal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AdminPageTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aplb))
        );

        AdminPageTabs.getAccessibleContext().setAccessibleName("Patient Details");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aplbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplbActionPerformed
        new FrontPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aplbActionPerformed

    private void apddcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apddcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apddcb1ActionPerformed

    private void apddgcbf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apddgcbf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apddgcbf1ActionPerformed

    private void appdfnf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdfnf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdfnf2ActionPerformed

    private void appdlnf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdlnf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdlnf2ActionPerformed

    private void apddcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apddcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apddcbActionPerformed

    private void apddgcbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apddgcbfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apddgcbfActionPerformed

    private void appdfnf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdfnf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdfnf1ActionPerformed

    private void appdlnf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdlnf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdlnf1ActionPerformed

    private void appdcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdcbActionPerformed

    private void appdgcbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdgcbfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdgcbfActionPerformed

    private void appdfnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdfnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdfnfActionPerformed

    private void appdlnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdlnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appdlnfActionPerformed

    private void adsridtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adsridtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adsridtfActionPerformed

    private void apddgcbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apddgcbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apddgcbmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminPageTabs;
    private javax.swing.JTextField adsridtf;
    private javax.swing.JLabel apal;
    private javax.swing.JPanel apapt;
    private javax.swing.JPanel apapt1;
    private javax.swing.JPanel apapt2;
    private javax.swing.JButton apddab;
    private javax.swing.JButton apddab1;
    private javax.swing.JButton apddcb;
    private javax.swing.JButton apddcb1;
    private javax.swing.JLabel apdddob;
    private javax.swing.JLabel apdddob1;
    private javax.swing.JLabel apddemad;
    private javax.swing.JLabel apddemad1;
    private javax.swing.JLabel apddemad2;
    private javax.swing.JCheckBox apddgcbf;
    private javax.swing.JCheckBox apddgcbf1;
    private javax.swing.JCheckBox apddgcbm;
    private javax.swing.JCheckBox apddgcbm1;
    private javax.swing.JLabel apddlg;
    private javax.swing.JLabel apddlg1;
    private javax.swing.JLabel apddln;
    private javax.swing.JLabel apddln1;
    private javax.swing.JLabel apddnl;
    private javax.swing.JLabel apddnl1;
    private javax.swing.JPanel apddt;
    private javax.swing.JLabel apddtpno;
    private javax.swing.JLabel apddtpno1;
    private javax.swing.JButton aplb;
    private javax.swing.JButton appdab;
    private javax.swing.JButton appdcb;
    private javax.swing.JLabel appddob;
    private javax.swing.JTextField appddobs;
    private javax.swing.JTextField appddobs1;
    private javax.swing.JTextField appddobs2;
    private javax.swing.JLabel appdemad;
    private javax.swing.JTextField appdemadd;
    private javax.swing.JTextField appdemadd1;
    private javax.swing.JTextField appdemadd2;
    private javax.swing.JTextField appdemadd3;
    private javax.swing.JTextField appdfnf;
    private javax.swing.JTextField appdfnf1;
    private javax.swing.JTextField appdfnf2;
    private javax.swing.JCheckBox appdgcbf;
    private javax.swing.JCheckBox appdgcbm;
    private javax.swing.JLabel appdlg;
    private javax.swing.JLabel appdln;
    private javax.swing.JTextField appdlnf;
    private javax.swing.JTextField appdlnf1;
    private javax.swing.JTextField appdlnf2;
    private javax.swing.JLabel appdnl;
    private javax.swing.JPanel appdt;
    private javax.swing.JTextField appdtlpno;
    private javax.swing.JTextField appdtlpno1;
    private javax.swing.JTextField appdtlpno2;
    private javax.swing.JLabel appdtpno;
    private javax.swing.JLabel appdvpfl1;
    private javax.swing.JLabel appdvpfl2;
    private javax.swing.JLabel appdvpfl3;
    private javax.swing.JLabel appdvpfl4;
    private javax.swing.JLabel appdvpfl5;
    private javax.swing.JLabel appdvpfl6;
    private javax.swing.JLabel appdvpfl7;
    private javax.swing.JLabel appdvpfl8;
    private javax.swing.JPanel aprdt;
    private javax.swing.JTextField apsplntf;
    private javax.swing.JTextField apsplntf1;
    private javax.swing.JTextField apsplntf2;
    private javax.swing.JTextField apsppid;
    private javax.swing.JTextField apsppid1;
    private javax.swing.JButton apspsb;
    private javax.swing.JButton apspsb1;
    private javax.swing.JButton apspsb2;
    private javax.swing.JTextField apsptf;
    private javax.swing.JTextField apsptf1;
    private javax.swing.JTextField apsptf2;
    private javax.swing.JLabel apvdl;
    private javax.swing.JLabel apvdl1;
    private javax.swing.JLabel apvpl;
    private javax.swing.JLabel apvplf;
    private javax.swing.JLabel apvplf1;
    private javax.swing.JLabel apvplf2;
    private javax.swing.JPanel apvpt;
    private javax.swing.JPanel apvpt1;
    private javax.swing.JPanel apvpt2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
